### ISSUE TITLE
Configure tmate port number

### ISSUE THREAD

**Issue by tyler36** [ddev/ddev-addon-template#44]
Maybe beyond the scope of this addon.

I tried to follow the instructions to debug an addon but get a `nyc1.tmate.io port 22: Connection refuse` error.

Is the tmate port configurable with this addon? Is this something we can enable, document?

The website [talks about](https://tmate.io/) `~/.tmate.conf` and using:

```
set -g tmate-server-port 22
```

I had issues previously with Gitpod and port 22. It is not uncommon for IT departments to block 22 for "security reasons".

**Comment by rfay** [comment]
I use this all the time without trouble. Is port 22 blocked in your environment? Can you ssh to other hosts on the internet? It's not uncommon for local firewalls to block 22. When it does, you can use a jumphost to access via another port, but that would be fairly annoying for this usage.

**Comment by rfay** [comment]
Try `ssh rfay@jumphost.thefays.us` - you won't be able to get in, but it should connect.

**Comment by tyler36** [comment]
It does not connect.

```shell
$ ssh rfay@jumphost.thefays.us
ssh: connect to host jumphost.thefays.us port 22: Connection refused
```

**Comment by rfay** [comment]
I guess you sorted that out before I even responded, and I fully encourage you to try out the tmate instructions for using a different port.

**Comment by tyler36** [comment]
I will play around and see what I can do.
