### ISSUE TITLE
How to add a config.*.yaml

### ISSUE THREAD

**Issue by simesy** [ddev/ddev-addon-template#47]
I understand an addon can have a yaml that gets merged into the main config but I'm not sure how this is named/etc. I would be good to have an example in this template.

**Comment by tyler36** [comment]
The only addon I regularly use with a `config` is https://github.com/ddev/ddev-selenium-standalone-chrome.
But you can easily practise your own configs:

1. Create a new project.
2. Create a new config file: `.ddev/config.db-port.yaml`  (or install the above add-on)

```yml
# .ddev/config.db-port.yaml
# Set a static DB port for the host
host_db_port: 49011
```

3. Restart DDEV and search `./.ddev/.ddev-docker-compose-full.yaml` for the config settings.

`./.ddev/.ddev-docker-compose-full.yaml` is the DDEV project; all the config associated with all the containers and services. So you can see exactly where settings are incorporated.

**Comment by rfay** [comment]
If you have extra config to add and install with an add-on you just
1. Test the `config.<whatever>.yaml` locally - see https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#extending-configyaml-with-custom-configyaml-files
2. Add the `config.<whatever>.yaml` to your add-on
3. Add it to your install.yaml

Changing config as always requires a restart, so all add-ons expect a `ddev restart` after getting them.

**Comment by simesy** [comment]
Thanks, i added it to the project_files section of the install.yaml
https://github.com/simesy/ddev-drupal-core-dev/blob/make-ddev-config/install.yaml#L6

**Comment by tyler36** [comment]
Sorry, for some reason, I read the OP as "I don't understand how the config is merged". It's been a day.

**Comment by simesy** [comment]
Haha nw. My head is full so I'm just skating along :D
