### ISSUE TITLE
Typo DDEV_NON_INTERACTIVE => DDEV_NONINTERACTIVE ?

### ISSUE THREAD

**Issue by julienloizelet** [ddev/ddev-addon-template#57]
Should the DDEV_NON_INTERACTIVE variable be renamed into DDEV_NONINTERACTIVE here: https://github.com/ddev/ddev-addon-template/blob/main/tests/test.bats#L7 ?

I ask because I came across this: https://github.com/ddev/github-action-add-on-test/blob/main/action.yaml#L102

Thanks

**Comment by stasadev** [comment]
Yes, it should be `DDEV_NONINTERACTIVE` everywhere.

Thank you for noticing this! Feel free to open a PR.
