### ISSUE TITLE
Update bats tests to add the "release" tag

### ISSUE THREAD

**Issue by julienloizelet** [ddev/ddev-addon-template#59]
Since https://github.com/ddev/github-action-add-on-test/releases/tag/v2.1.0, user can exclude "release" tagged tests from pull request workflow.

As it is the default expected behavior, we should update the bats tests accordingly ([here](https://github.com/ddev/ddev-addon-template/blob/main/tests/test.bats#L36)): 

```
# bats test_tags=release
@test "install from release" {
...
...
}
```

**Comment by tyler36** [comment]
Fixed in #58

**Comment by tyler36** [comment]
#58 was merged so this can be closed now.

**Comment by tyler36** [comment]
Thank you. I didn't have permission to close this otherwise I would have do it myself. :)
