### ISSUE TITLE
Update "Contributed and maintained by"

### ISSUE THREAD

**Issue by julienloizelet** [ddev/ddev-addon-template#60]
I don't know what could be used, but the current “@contributor” is a real user who hasn't contributed :)

**Comment by tyler36** [comment]
Oh, your right! 

Maybe something like `@contributor-name-here` ?

**Comment by julienloizelet** [comment]
Indeed, It looks like wrapping the @... in backticks will prevent GitHub from turning it into a link.

I'm not sure what is the best option ...

Just changing the current sentence to "Contributed and maintained by `@contributor`" should be enough :)

**Comment by tyler36** [comment]
If wrapping works, I think that's a great solution.

Want to make a PR?

**Comment by julienloizelet** [comment]
> If wrapping works, I think that's a great solution.
> 
> Want to make a PR?

Sure, I'll will open a PR asap (probably with a fix for [this one](https://github.com/ddev/ddev-addon-template/issues/57) too)

Thanks
